Start prefect ui:
  prefect server start
Create Blocks (Storage, Process):
  python blx.py
How to Learn blocks-slug to use create Deployments:
  prefect blocks ls
  -sb {local-file-system/slug}
  -ib {process/slug}
Create Deployments with terminal:
  prefect deployment build 
  -n titanic-dep 
  -sb local-file-system/titanic-storage-block 
  -ib process/titanic-process-infra 
  Transform.py:main --apply
How to start agent:
  prefect agent start -q 'default'